---
title: "ex2 Roee Lopata"
author: "Roee Lopata"
date: "4 11 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r - DELETE}
library("compGenomRData")

counts_file <- system.file("extdata/rna-seq/SRP029880.raw_counts.tsv",
                           package = "compGenomRData")
coldata_file <- system.file("extdata/rna-seq/SRP029880.colData.tsv",
                            package = "compGenomRData")


counts_df <- read.table(counts_file, header = T, sep = '\t')
counts_mat <- as.matrix(counts_df)
geneLengths_mat <- subset(counts_mat, select = c(width))
geneLengths_vector <- as.vector(geneLengths_mat)

rpkm <- apply(X = subset(counts_mat, select = c(-width)),
              MARGIN = 2,
              FUN = function(x) {
              (x * 10^9) / (geneLengths_vector * sum(as.numeric(x)))
              })

colSums(rpkm)

#normalize by the sample size using rpkm values
tpm <- apply(rpkm, 2, function(x) {(x / sum(as.numeric(x))) * 10^6})

colSums(tpm)
```


```{r - Q2}
V = apply(tpm, 1, var)
selectedGenes500 = names(V[order(V, decreasing = T)][1:500])

library(pheatmap)
pheatmap(tpm[selectedGenes500,], scale = 'row', show_rownames = FALSE)

selectedGenes100 = names(V[order(V, decreasing = T)][1:100])
pheatmap(tpm[selectedGenes100,], scale = 'row', show_rownames = FALSE)

```

```{r - Q3}
pheatmap(tpm[selectedGenes100,], scale = 'none', show_rownames = FALSE)

pheatmap(tpm[selectedGenes100,], scale = 'column', show_rownames = FALSE)
```

```{r - Q4}
library(stats)
correlationMatrix = cor(tpm)

library(corrplot)
corrplot(correlationMatrix, order = 'hclust', 
         addrect = 2, addCoef.col = 'white', 
         number.cex = 0.7) 
```

```{r - Q5}
tot_expression = rowSums(tpm)

top_expressed = names(tot_expression[order(tot_expression, decreasing = T)][1:100])

pheatmap(tpm[top_expressed,], scale = 'row', show_rownames = FALSE)

correlationMatrix_Q5 = cor(tpm[top_expressed,])
corrplot(correlationMatrix_Q5, order = 'hclust', 
         addrect = 2, addCoef.col = 'white', 
         number.cex = 0.7) 

```

```{r - Q6}
colData = read.table(coldata_file, header = T, sep = '\t', 
                      stringsAsFactors = TRUE)
library(stats)
library(ggplot2)
library(ggfortify)

pheatmap(correlationMatrix,  
         annotation_col = colData, 
         cutree_cols = 2)

M <- t(tpm[selectedGenes500,])

M <- log2(M + 1)

pcaResults <- prcomp(M)

autoplot(pcaResults, data = colData, colour = 'group')

```

```{r - Q7}
counts_filtered_df = counts_df[apply(counts_df, MARGIN = 1, FUN = function(x) sd(x) != 0),]

pheatmap(counts_filtered_df, scale = 'row', show_rownames = FALSE)
```